
export const fitnessQuotes = [
  "The only bad workout is the one that didn't happen.",
  "Your body can do it. It's your mind you have to convince.",
  "Fitness is not about being better than someone else. It's about being better than you used to be.",
  "Don't wish for it, work for it.",
  "The groundwork for all happiness is good health.",
  "Take care of your body. It's the only place you have to live.",
  "Success isn't given. It's earned in the gym.",
  "A healthy outside starts from the inside.",
  "You don't have to be extreme, just consistent.",
  "The first wealth is health.",
  "Stronger than yesterday, weaker than tomorrow.",
  "Fitness is like a relationship. You can't cheat and expect it to work.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Your only limit is your mind.",
  "Sweat is fat crying.",
  "Make yourself proud.",
  "Every workout is progress.",
  "Champions train, losers complain.",
  "Your health is an investment, not an expense.",
  "Be stronger than your excuses.",
  "Progress, not perfection.",
  "What seems impossible today will one day become your warm-up.",
  "The body achieves what the mind believes.",
  "You're only one workout away from a good mood.",
  "Discipline is choosing between what you want now and what you want most.",
  "Fall in love with taking care of yourself.",
  "A strong body makes the mind strong.",
  "You don't get what you wish for, you get what you work for.",
  "Push yourself because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "The only impossible journey is the one you never begin.",
  "Your body is a temple. Keep it pure and clean for the soul to reside in.",
  "Fitness is not a destination, it's a way of life.",
  "Every master was once a disaster.",
  "You are what you repeatedly do.",
  "The hard days are what make you stronger.",
  "Believe in yourself and all that you are.",
  "Success starts with self-discipline.",
  "Your potential is endless.",
  "Mind over matter. If you don't mind, it doesn't matter.",
  "Be patient with yourself. Nothing in nature blooms all year.",
  "The difference between try and triumph is a little umph.",
  "You are capable of amazing things.",
  "Don't stop when you're tired, stop when you're done.",
  "The comeback is always stronger than the setback.",
  "Train insane or remain the same.",
  "Your health is worth fighting for.",
  "Small progress is still progress.",
  "Wake up with determination, go to bed with satisfaction.",
  "You're not just working out, you're building a better version of yourself.",
  "The struggle you're in today is developing the strength you need tomorrow.",
  "Exercise is a celebration of what your body can do, not a punishment for what you ate.",
  "Healthy is not a size, it's a lifestyle.",
  "Your fitness is 100% mental. Your body won't go where your mind doesn't push it.",
  "Excuses don't burn calories.",
  "The only bad decision is not making one at all.",
  "You are your only competition.",
  "Champions keep playing until they get it right.",
  "The clock is ticking. Are you becoming the person you want to be?",
  "Transform your body, transform your life.",
  "Consistency is key to success.",
  "Make your health a priority.",
  "Every step counts, every rep matters.",
  "Today's workout is tomorrow's strength.",
  "Push your limits, break your barriers.",
  "Health is not about the weight you lose, but about the life you gain.",
  "Strive for progress, not perfection.",
  "You are stronger than you think.",
  "Focus on being healthy, not skinny.",
  "The best project you'll ever work on is you.",
  "Make time for making yourself better.",
  "Your future self will thank you.",
  "Embrace the process, trust the journey.",
  "Every day is a chance to get better.",
  "Train like a beast, look like a beauty.",
  "You don't have to be great to get started, but you have to get started to be great.",
  "The human body is the best picture of the human soul.",
  "Exercise is medicine for the mind, body, and soul.",
  "Strong people are harder to kill and more useful in general.",
  "The gym is my therapy.",
  "Fitness isn't a seasonal hobby. It's a lifestyle.",
  "You can't out-train a bad diet.",
  "Rest when you're weary. Refresh and renew yourself.",
  "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.",
  "The wise person should consider that health is the greatest of human blessings.",
  "To enjoy the glow of good health, you must exercise.",
  "Lack of activity destroys the good condition of every human being.",
  "Movement is medicine for creating change in a person's physical, emotional, and mental states.",
  "The groundwork for all happiness is good health.",
  "Health is a state of complete physical, mental and social well-being.",
  "Exercise to stimulate, not to annihilate. The world wasn't formed in a day, and neither were we.",
  "Take care of your body. It's the only place you have to live.",
  "A goal without a plan is just a wish.",
  "You miss 100% of the shots you don't take.",
  "Don't put off tomorrow what you can do today.",
  "The journey of a thousand miles begins with one step.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The way to get started is to quit talking and begin doing.",
  "Innovation distinguishes between a leader and a follower.",
  "Life is what happens to you while you're busy making other plans.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It is during our darkest moments that we must focus to see the light.",
  "Whoever is happy will make others happy too.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In the end, we will remember not the words of our enemies, but the silence of our friends.",
  "The purpose of our lives is to be happy.",
  "Life is really simple, but we insist on making it complicated.",
  "May you live all the days of your life.",
  "Life itself is the most wonderful fairy tale.",
  "Do not let making a living prevent you from making a life.",
  "Life is ours to be spent, not to be saved.",
  "Keep smiling, because life is a beautiful thing and there's so much to smile about.",
  "Life is a long lesson in humility.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "Love the life you live. Live the life you love.",
  "Life is either a daring adventure or nothing at all.",
  "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  "Believe you can and you're halfway there.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams! Live the life you've imagined.",
  "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.",
  "Try to be a rainbow in someone's cloud.",
  "You do not find the happy life. You make it.",
  "Happiness is not something readymade. It comes from your own actions.",
  "The most important thing is to enjoy your life—to be happy—it's all that matters.",
  "Happiness is when what you think, what you say, and what you do are in harmony.",
  "For every minute you are angry you lose sixty seconds of happiness.",
  "Happiness is not by chance, but by choice.",
  "Count your age by friends, not years. Count your life by smiles, not tears.",
  "Happiness is a warm puppy.",
  "The happiness of your life depends upon the quality of your thoughts.",
  "Time you enjoy wasting is not wasted time.",
  "Happiness is not something you postpone for the future; it is something you design for the present.",
  "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future, but to live the present moment wisely and earnestly.",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
  "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.",
  "The best way to cheer yourself is to try to cheer someone else up.",
  "Happiness lies in the joy of achievement and the thrill of creative effort.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The only way to do great work is to love what you do.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "Innovation distinguishes between a leader and a follower.",
  "Stay hungry, stay foolish.",
  "The way to get started is to quit talking and begin doing.",
  "Don't be afraid to give your best to what seemingly are small jobs.",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
  "Don't be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Try not to become a person of success, but rather try to become a person of value.",
  "It is better to fail in originality than to succeed in imitation.",
  "The road to success and the road to failure are almost exactly the same.",
  "Success is where preparation and opportunity meet.",
  "Don't be afraid to give your best to what seemingly are small jobs. Every time you conquer one it makes you that much stronger.",
  "I never dreamed about success, I worked for it.",
  "Success seems to be connected with action. Successful people keep moving.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "The way to achieve your own success is to be willing to help somebody else get it first.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Opportunities don't happen. You create them.",
  "Don't wait for opportunity. Create it.",
  "Success is not about being the best. It's about always getting better.",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
  "Success is about making your life a little better, and the lives of those around you a little better too.",
  "The most successful people are those who are good at plan B.",
  "Success is the ability to go from failure to failure without losing your enthusiasm.",
  "You are never too old to set another goal or to dream a new dream.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you've ever wanted is on the other side of fear.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "The most common way people give up their power is by thinking they don't have any.",
  "If you look at what you have in life, you'll always have more.",
  "If you look at what you don't have in life, you'll never have enough.",
  "It is during our darkest moments that we must focus to see the light.",
  "You must be the change you wish to see in the world.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "The only impossible journey is the one you never begin.",
  "In this life we cannot do great things. We can only do small things with great love.",
  "If you judge people, you have no time to love them.",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.",
  "I alone cannot change the world, but I can cast a stone across the water to create many ripples.",
  "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.",
  "You must not lose faith in humanity. Humanity is like an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty.",
  "A man is but the product of his thoughts. What he thinks, he becomes.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The weak can never forgive. Forgiveness is the attribute of the strong.",
  "Hate the sin, love the sinner.",
  "I will not let anyone walk through my mind with their dirty feet.",
  "Nobody can hurt me without my permission.",
  "Prayer is not asking. It is a longing of the soul. It is daily admission of one's weakness.",
  "A nation's culture resides in the hearts and in the soul of its people.",
  "Where there is love there is life.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "In a gentle way, you can shake the world.",
  "Change yourself – you are in control.",
  "You must learn to be still in the midst of activity and to be vibrantly alive in repose.",
  "A man who conquers himself is greater than one who conquers a thousand men in battle.",
  "The mind is everything. What you think you become.",
  "Peace comes from within. Do not seek it without.",
  "Better than a thousand hollow words, is one word that brings peace.",
  "If you truly loved yourself, you could never hurt another.",
  "You will not be punished for your anger, you will be punished by your anger.",
  "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.",
  "Three things cannot be long hidden: the sun, the moon, and the truth.",
  "The only real failure in life is not to be true to the best one knows.",
  "Believe nothing, no matter where you read it, or who said it, no matter if I have said it, unless it agrees with your own reason and your own common sense.",
  "Your purpose in life is to find your purpose and give your whole heart and soul to it.",
  "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
  "Every morning we are born again. What we do today is what matters most.",
  "The trouble is, you think you have time.",
  "If you want to know your past, look at your present condition. If you want to know your future, look at your present actions.",
  "Doubt everything. Find your own light.",
  "Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.",
  "If you are facing in the right direction, all you need to do is keep on walking.",
  "It is better to travel well than to arrive.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.",
  "To understand everything is to forgive everything.",
  "Hatred does not cease by hatred, but only by love; this is the eternal rule.",
  "Just as a mother would protect her only child with her life, even so let one cultivate a boundless love towards all beings.",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection.",
  "If you propose to speak always ask yourself, is it true, is it necessary, is it kind.",
  "A jug fills drop by drop.",
  "The way is not in the sky. The way is in the heart.",
  "What we think, we become.",
  "All things arise and pass away. When you see this, you are above sorrow. This is the clear path.",
  "May all beings have happy minds.",
  "Better it is to live one day seeing the rise and fall of things than to live a hundred years without ever seeing the rise and fall of things.",
  "The foot feels the foot when it feels the ground.",
  "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.",
  "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?",
  "Unity can only be manifested by the Binary. Unity itself and the idea of Unity are already two.",
  "Work out your salvation. Do not depend on others.",
  "Radiate boundless love towards the entire world.",
  "Set your heart on doing good. Do it over and over again, and you will be filled with joy.",
  "Should you find a wise critic to point out your faults, follow him as you would a guide to hidden treasure.",
  "Even death is not to be feared by one who has lived wisely.",
  "It is during our darkest moments that we must focus to see the light.",
  "Try to be a rainbow in someone's cloud.",
  "In the end, we will remember not the words of our enemies, but the silence of our friends.",
  "Injustice anywhere is a threat to justice everywhere.",
  "Life's most persistent and urgent question is: 'What are you doing for others?'",
  "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.",
  "Faith is taking the first step even when you can't see the whole staircase.",
  "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.",
  "Our lives begin to end the day we become silent about things that matter.",
  "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
  "Intelligence plus character—that is the goal of true education.",
  "The time is always right to do what is right.",
  "We must accept finite disappointment, but never lose infinite hope.",
  "I have a dream that my four little children will one day live in a nation where they will not be judged by the color of their skin, but by the content of their character.",
  "Nothing in the world is more dangerous than sincere ignorance and conscientious stupidity.",
  "The ultimate tragedy is not the oppression and cruelty by the bad people but the silence over that by the good people.",
  "We must learn to live together as brothers or perish together as fools.",
  "Love is the only force capable of transforming an enemy into a friend.",
  "Forgiveness is not an occasional act, it is a constant attitude.",
  "We must build dikes of courage to hold back the flood of fear.",
  "Human progress is neither automatic nor inevitable... Every step toward the goal of justice requires sacrifice, suffering, and struggle; the tireless exertions and passionate concern of dedicated individuals.",
  "The function of education is to teach one to think intensively and to think critically. Intelligence plus character - that is the goal of true education.",
  "A genuine leader is not a searcher for consensus but a molder of consensus.",
  "I believe that unarmed truth and unconditional love will have the final word in reality. This is why right, temporarily defeated, is stronger than evil triumphant.",
  "A man can't ride your back unless it's bent.",
  "Everything that is done in the world is done by hope.",
  "Commit yourself to the noble struggle for equal rights. You will make a greater person of yourself, a greater nation of your country, and a finer world to live in.",
  "We are not makers of history. We are made by history.",
  "A right delayed is a right denied.",
  "Keep feeling the need for being important. Keep feeling the need for being first. But I want you to be the first in love. I want you to be the first in moral excellence. I want you to be the first in generosity.",
  "There comes a time when one must take a position that is neither safe, nor politic, nor popular, but he must take it because conscience tells him it is right.",
  "The art of acceptance is the art of making someone who has just done you a small favor wish that he might have done you a greater one.",
  "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
  "Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation.",
  "Be yourself; everyone else is already taken.",
  "I am so clever that sometimes I don't understand a single word of what I am saying.",
  "We are all in the gutter, but some of us are looking at the stars.",
  "Always forgive your enemies; nothing annoys them so much.",
  "What is a cynic? A man who knows the price of everything and the value of nothing.",
  "Experience is merely the name men gave to their mistakes.",
  "I can resist everything except temptation.",
  "When I was young I thought that money was the most important thing in life; now that I am old I know that it is.",
  "Some cause happiness wherever they go; others whenever they go.",
  "The only way to get rid of a temptation is to yield to it.",
  "I have the simplest tastes. I am always satisfied with the best.",
  "Work is the curse of the drinking classes.",
  "I never travel without my diary. One should always have something sensational to read in the train.",
  "The world is a stage, but the play is badly cast.",
  "Fashion is what one wears oneself. What is unfashionable is what other people wear.",
  "A thing is not necessarily true because a man dies for it.",
  "Arguments are extremely vulgar, for everyone in good society holds exactly the same opinion.",
  "True friends stab you in the front.",
  "Quotation is a serviceable substitute for wit.",
  "The only thing worse than being talked about is not being talked about.",
  "We live in an age when unnecessary things are our only necessities.",
  "Anyone who lives within their means suffers from a lack of imagination.",
  "When poverty comes in at the door, love flies out of the window.",
  "Memory... is the diary that we all carry about with us.",
  "Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.",
  "A dreamer is one who can only find his way by moonlight, and his punishment is that he sees the dawn before the rest of the world.",
  "Education is an admirable thing, but it is well to remember from time to time that nothing that is worth knowing can be taught.",
  "The good ended happily, and the bad unhappily. That is what fiction means.",
  "I think that God, in creating man, somewhat overestimated his ability.",
  "Patriotism is the virtue of the vicious.",
  "Democracy means simply the bludgeoning of the people by the people for the people.",
  "Consistency is the last refuge of the unimaginative.",
  "Moderation is a fatal thing. Nothing succeeds like excess.",
  "The heart was made to be broken.",
  "When good Americans die, they go to Paris.",
  "The basis of optimism is sheer terror.",
  "No good deed goes unpunished.",
  "The public is wonderfully tolerant. It forgives everything except genius.",
  "Sarcasm is the lowest form of wit, but the highest form of intelligence.",
  "Genius is one percent inspiration and ninety-nine percent perspiration.",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
  "The value of an idea lies in the using of it.",
  "There's a way to do it better - find it.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
  "The three great essentials to achieve anything worthwhile are: Hard work, Stick-to-itiveness, and Common sense.",
  "Genius is one percent inspiration, ninety-nine percent perspiration.",
  "Results! Why, man, I have gotten a lot of results. I know several thousand ways that won't work.",
  "Show me a thoroughly satisfied man and I will show you a failure.",
  "Being busy does not always mean real work. The object of all work is production or accomplishment and to either of these ends there must be forethought, system, planning, intelligence, and honest purpose, as well as perspiration.",
  "The doctor of the future will give no medicines, but will interest his patients in the care of the human frame, in diet, and in the cause and prevention of disease.",
  "To my mind the old masters are not art; their value is in their scarcity.",
  "Hell, there are no rules here - we're trying to accomplish something.",
  "What you are will show in what you do.",
  "Vision without execution is just hallucination.",
  "I find out what the world needs. Then I go ahead and try to invent it.",
  "Tomorrow is the first day of the rest of your life.",
  "Just because something doesn't do what you planned it to do doesn't mean it's useless.",
  "There ain't no rules around here! We're trying to accomplish something!",
  "Non-violence leads to the highest ethics, which is the goal of all evolution. Until we stop harming all other living beings, we are still savages.",
  "The chief function of the body is to carry the brain around.",
  "Everything should be made as simple as possible, but not simpler.",
  "Imagination is more important than knowledge.",
  "Reality is merely an illusion, albeit a very persistent one.",
  "The important thing is not to stop questioning. Curiosity has its own reason for existing.",
  "Anyone who has never made a mistake has never tried anything new.",
  "Try not to become a man of success, but rather try to become a man of value.",
  "Great spirits have always encountered violent opposition from mediocre minds.",
  "The difference between genius and stupidity is; genius has its limits.",
  "We cannot solve our problems with the same thinking we used when we created them.",
  "A person who never made a mistake never tried anything new.",
  "Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "Only a life lived for others is a life worthwhile.",
  "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.",
  "I have no special talent. I am only passionately curious.",
  "The only source of knowledge is experience.",
  "Information is not knowledge.",
  "Peace cannot be kept by force; it can only be achieved by understanding.",
  "Look deep into nature, and then you will understand everything better.",
  "A clever person solves a problem. A wise person avoids it.",
  "Science without religion is lame, religion without science is blind.",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
  "Black holes are where God divided by zero.",
  "Pure mathematics is, in its way, the poetry of logical ideas.",
  "God does not play dice with the universe.",
  "The secret to creativity is knowing how to hide your sources.",
  "Weakness of attitude becomes weakness of character.",
  "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
  "It's not what happens to you, but how you react to it that matters.",
  "No man is free who is not master of himself.",
  "Wealth consists in not having great possessions, but in having few wants.",
  "He who is not satisfied with a little, is satisfied with nothing.",
  "Don't explain your philosophy. Embody it.",
  "You have power over your mind - not outside events. Realize this, and you will find strength.",
  "The best revenge is not to be like your enemy.",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
  "When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.",
  "The universe is change; our life is what our thoughts make it.",
  "Waste no more time arguing what a good man should be. Be one.",
  "If you seek tranquillity, do less. Or more accurately, do what's essential... Which brings a double satisfaction: to do less, better.",
  "You were born to work together with others. Find people who share your values, and you'll conquer the world.",
  "The happiness of your life depends upon the quality of your thoughts.",
  "Confine yourself to the present.",
  "Accept the things to which fate binds you, and love the people with whom fate brings you together.",
  "The soul becomes dyed with the color of its thoughts.",
  "Be tolerant with others and strict with yourself.",
  "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.",
  "What we do now echoes in eternity.",
  "Remember that very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
  "Forward, as occasion offers. Never look round to see whether any shall note it... Be satisfied with success in even the smallest matter, and think that even such a result is no trifle.",
  "How much trouble he avoids who does not look to see what his neighbor says or does.",
  "The best revenge is massive success.",
  "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
  "Limits, like fear, is often an illusion.",
  "I can accept failure, everyone fails at something. But I can't accept not trying.",
  "Talent wins games, but teamwork and intelligence wins championships.",
  "Some people want it to happen, some wish it would happen, others make it happen.",
  "If you're trying to achieve, there will be roadblocks. I've had them; everybody has had them. But obstacles don't have to stop you. If you run into a wall, don't turn around and give up. Figure out how to climb it, go through it, or work around it.",
  "I've always believed that if you put in the work, the results will come.",
  "My attitude is that if you push me towards something that you think is a weakness, then I will turn that perceived weakness into a strength.",
  "Just play. Have fun. Enjoy the game.",
  "Step by step. I can't think of any other way of accomplishing anything.",
  "Always turn a negative situation into a positive situation.",
  "You must expect great things of yourself before you can do them.",
  "The strength of the team is each individual member. The strength of each member is the team.",
  "Excellence is not a skill. It is an attitude.",
  "Champions keep playing until they get it right.",
  "You have to expect things of yourself before you can do them.",
  "To be a champ, you have to believe in yourself when nobody else will.",
  "A champion is someone who gets up when he can't.",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
  "Perfection is not attainable, but if we chase perfection we can catch excellence.",
  "It's not whether you get knocked down, it's whether you get up.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will."
];

export const getDailyQuote = (): string => {
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
  const quoteIndex = (dayOfYear - 1) % fitnessQuotes.length;
  return fitnessQuotes[quoteIndex];
};

export const getFirstName = (fullName: string): string => {
  return fullName.split(' ')[0];
};
